### ISSUE TITLE
Marked.js error: while (this.next().type !== 'list_item_end') 

### ISSUE THREAD

**Issue by machal** [jacobrask/styledocco#122]
styledocco worked well but now I am getting this error message.

Any ideas where I can start debugging?

```
Running "styledocco:dist" (styledocco) task
>> Error: 
>> /usr/local/lib/node_modules/styledocco/node_modules/marked/lib/marked.js:951
>>       while (this.next().type !== 'list_item_end') {
>>                         ^
>> TypeError: Cannot read property 'type' of undefined
>>     at Parser.tok (/usr/local/lib/node_modules/styledocco/node_modules/marked/lib/marked.js:951:25)
>>     at Parser.tok (/usr/local/lib/node_modules/styledocco/node_modules/marked/lib/marked.js:937:22)
>>     at Parser.parse (/usr/local/lib/node_modules/styledocco/node_modules/marked/lib/marked.js:797:17)
>>     at Function.Parser.parse [as parser] (/usr/local/lib/node_modules/styledocco/node_modules/marked/lib/marked.js:784:17)
>>     at /usr/local/lib/node_modules/styledocco/styledocco.js:155:35
>>     at Array.map (native)
>>     at exports.makeSections (/usr/local/lib/node_modules/styledocco/styledocco.js:150:6)
>>     at module.exports (/usr/local/lib/node_modules/styledocco/styledocco.js:162:10)
>>     at /usr/local/lib/node_modules/styledocco/cli.js:289:22
>>     at fs.js:271:14
>> Code: 8
```

**Comment by vrusua** [comment]
Have the same error. Any progress?

**Comment by MichalSvatos** [comment]
Bump. I have the same problem on Windows with StyleDocco (and KSS). On Linux there is also error - almost identical.

**Comment by machal** [comment]
I've found one issue with Marked.js and its LESS sources parsing.  

I had this Markdown in one of my LESS files:

```
* #content removal
```

Then I tried change it to this:

```
* `#content` removal
```

…and it works. I think there is problem with ugly Mardown syntax. Can you try it?

**Comment by MichalSvatos** [comment]
I don't even have that line in Marked.js. Anywhere actually :-/ I gone through all files in "...\AppData\Roaming\npm\node_modules\" and local folder but no luck.

**Comment by machal** [comment]
Ah, sorry, could explain it better.
I wrote about Markdown content in _my_ LESS files. I've changed previous comment too.

**Comment by MichalSvatos** [comment]
Well... I found this. 
`styledocco --init`
Doesn't work.
`kss-node --init`
Either. ...BUT

`kss-node folderwithlessfiles styleguide --less actual/file.less`
Create documentation. You have to manually add the _styleguide.md_ tho.
