### ISSUE TITLE
throw new TypeError('Path must be a string. Received ' + inspect(path));

### ISSUE THREAD

**Issue by IrvingArmenta** [jacobrask/styledocco#134]
Hello, just installed and tried to see how styledocco works but I keep getting this error:

`"throw new TypeError('Path must be a string. Received ' + inspect(path));" `

I'm using it with Gulp (gulp-styledocco), however, I also tried to use it directly on the command line and I keep getting that error. 
This is the output I get from "gulp-styledocco" 
`styledocco --out ./build/css/ --name "Herdez" --no-minify /Users/krrrunch/Code/herdez-front/build/css/main.css`

I'm pretty sure I installed it correctly with npm install -fg styledocco

this is my gulp function

```
gulp.task('styledocco',  function () {
  gulp.src('./build/css/*.css')
    .pipe(styledocco({
      out: './build/css/',
      name: 'Herdez',
      'no-minify': true
    }));
});
```
I know this is not the gulp-styledocco repository but I really think is a styledocco issue.

Any ideas?

**Comment by oZeca** [comment]
Having the same issue here.

I'm runing `styledocco -n "sassdoc" sass`, where "sass" is the folder with scss files.
And it throws:
 

> ath.js:7
>     throw new TypeError('Path must be a string. Received ' + inspect(path));
>     ^
> 
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.extname (path.js:1431:5)
>     at /usr/local/lib/node_modules/styledocco/cli.js:222:48
>     at Array.filter (native)
>     at /usr/local/lib/node_modules/styledocco/cli.js:221:37
>     at tryToString (fs.js:455:3)
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
> 

Help would be appreciated.
Thanks

**Comment by BenGlassAtlas** [comment]
Same here, even with a simple use scenario such as `styledocco -n "My Project" src`

**Comment by BenGlassAtlas** [comment]
Downgrading my Node version via NVM fixed this for me, I downgraded from `6.6.0` to `5.0.0` and it worked fine.
