### ISSUE TITLE
RangeError with ncss

### ISSUE THREAD

**Issue by chrisjaure** [jacobrask/styledocco#34]
After upgrading to 0.4, I can't generate docs due to this issue with ncss:

```
/home/chrisjaure/.nvm/v0.8.1/lib/node_modules/styledocco/node_modules/ncss/lib/parser.js:270
          if (!property || KEYWORDS.indexOf(t) >= 0) q(t);
                                    ^
RangeError: Maximum call stack size exceeded
```

I've got a lot of css files, and it seems to be failing on some jquery ui styles, which I don't really even need to be documented. Is there a way to exclude files?

**Comment by jacobrask** [comment]
Ok, I'll look into testing with huge CSS files, I know at least one optimization I can do.

For now you could use `find` instead of passing in a directory to StyleDocco. Something like:

```
styledocco -n Name $(find . -name "*.css" -not -path "*jquery*")
```

Let me know how that works out

**Comment by chrisjaure** [comment]
Works great. Thanks!

(I really need to get better at Bash.)

**Comment by jacobrask** [comment]
I disabled ncss for now, until the bugs are fixed or I find another minifier that's fast enough

**Comment by vosnikopa** [comment]
Hey Jacob, amazing work ... 

same problem here... we have a gozilla size css monster to deal with . 

the command i use is:
--> styledocco -n "styleguide" -o "assets/stylesheets"

/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:76
        f.apply(cb, context.stack);
          ^
RangeError: Maximum call stack size exceeded
    at action (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:76:11)
    at next (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:208:17)
    at seqEach (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:213:30)
    at cb (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:55:24)
    at Function.<anonymous> (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/index.js:75:29)
    at Function.seqEach (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:210:38)
    at action (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:76:11)
    at next (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:208:17)
    at seqEach (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:213:30)
    at cb (/usr/local/share/npm/lib/node_modules/styledocco/node_modules/findit/node_modules/seq/index.js:55:24)

any ideas.... 

thanks in advance from greece ;)
