### ISSUE TITLE
Child Process Error

### ISSUE THREAD

**Issue by jrutter** [jacobrask/styledocco#66]
Hi there,

Im trying to run styledocco on a directory of sass files and am getting this error:

styledocco -n "grapevine" sass

child_process.js:444
    throw errnoException(errno, 'spawn');
    ^
Error: spawn EMFILE
    at errnoException (child_process.js:481:11)
    at ChildProcess.spawn (child_process.js:444:11)
    at child_process.js:342:9
    at Object.execFile (child_process.js:252:15)
    at child_process.js:220:18
    at /usr/local/lib/node_modules/styledocco/cli.js:110:5
    at Object.css (/usr/local/lib/node_modules/styledocco/node_modules/async/lib/async.js:532:23)
    at /usr/local/lib/node_modules/styledocco/node_modules/async/lib/async.js:467:24
    at /usr/local/lib/node_modules/styledocco/node_modules/async/lib/async.js:86:13
    at Array.forEach (native)

Any ideas?

**Comment by marrs** [comment]
Do you have a large number of sass files?  Could it be related to #52?
