### ISSUE TITLE
Cannot find "highlight.js"

### ISSUE THREAD

**Issue by sereby** [jacobrask/styledocco#7]
When attempting to run styledocco, I get the following error:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'highlight.js'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (C:\Users\Machine\AppData\Roaming\npm\node_modules\styledocco\lib\parser.js:6:15)
    at Object.<anonymous> (C:\Users\Machine\AppData\Roaming\npm\node_modules\styledocco\lib\parser.js:111:4)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)

**Comment by jacobrask** [comment]
It was a missing dependency, sorry about that, it should work now.
